### ISSUE TITLE
Recommended reading

### ISSUE THREAD

**Issue by deardooley** [damjanmk/Raccoon2#2]
Good project. Thanks for the talk at IWSG17 on Raccoon. If you get a moment, you might be interested in a side project a colleague of mine built. https://drugdiscovery.tacc.utexas.edu/#/home. It's a small angularjs app with an express proxy to restrict usage to a handful of users. I just point it out because it runs autodock vina, scales horizontally, and can leverage computational resources locally, in public and private clouds, HPC environments, etc. It might be something you can leverage to accelerate your work on Raccoon.

**Comment by damjanmk** [comment]
Thanks @deardooley!
